/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BussinesModelLayer.Contactos;
import BussinesModelLayer.Proveedores;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author mario
 */
public class frmNMProveedores extends javax.swing.JDialog {
     private int idProveedor = 0;//boton modificar
     private Proveedores proveedores = new Proveedores();//boton modificar
     private int tablaIdContactoClass[];
    /**
     * Creates new form frmNMProveedores
     */
    public frmNMProveedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public frmNMProveedores(){
        initComponents();
        Contactos contacto = new Contactos();
        DefaultTableModel resultadoContacto = contacto.GetAllModel();
        int NumFilasContacto = resultadoContacto.getRowCount();
        int tablaIdContacto[];
        tablaIdContacto = new int[NumFilasContacto];
        String tablaNombreContacto[];
        tablaNombreContacto = new String[NumFilasContacto];
        int indexSelectedContacto = 0;
        
        for (int i = 0; i < NumFilasContacto; i++) {
            tablaIdContacto[i] = (int) resultadoContacto.getValueAt(i, 0);
            tablaNombreContacto[i] = (String) resultadoContacto.getValueAt(i, 1);
            comboBoxIdContacto.addItem(tablaNombreContacto[i]);
        }
        this.tablaIdContactoClass = new int[NumFilasContacto];
        this.tablaIdContactoClass = tablaIdContacto;
    }
    public frmNMProveedores(int idProveedor) {//boton modificar
        initComponents();
        this.idProveedor = idProveedor;//se le pone la unica propiedad que es idProducto pero es la unica propiedad que ocupa para poder llamar al metodo GetById() y este metodo lo que hace es poblar las otras propiedades con la informacion de la base de datos
        proveedores.setIdProveedor(idProveedor);
        proveedores.GetById();//recuerda que este metodo lo que hacia era consultar en base de datos y llenar las mismas propiedades de este objeto de la misma clase
        txtNombreProveedor.setText(proveedores.getNombreProveedor());
        //txtIdContacto.setText("" + proveedores.getIdContacto());
        
        Contactos contacto = new Contactos();
        DefaultTableModel resultadoContacto = contacto.GetAllModel();
        int NumFilasContacto = resultadoContacto.getRowCount();
        int tablaIdContacto[];
        tablaIdContacto = new int[NumFilasContacto];
        String tablaNombreContacto[];
        tablaNombreContacto = new String[NumFilasContacto];
        int indexSelectedContacto = 0;
        
         for (int i = 0; i < NumFilasContacto; i++) {
            tablaIdContacto[i] = (int) resultadoContacto.getValueAt(i, 0);
            tablaNombreContacto[i] = (String) resultadoContacto.getValueAt(i, 1);
            comboBoxIdContacto.addItem(tablaNombreContacto[i]);
            if (tablaIdContacto[i] == proveedores.getIdContacto()) {
                indexSelectedContacto = i;
            }
        }
        comboBoxIdContacto.setSelectedIndex(indexSelectedContacto);
        this.tablaIdContactoClass = new int[NumFilasContacto];
        this.tablaIdContactoClass = tablaIdContacto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        txtNombreProveedor = new javax.swing.JTextField();
        comboBoxIdContacto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Proveedor");

        jLabel2.setText("Contacto");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnOk.setText("Guardar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxIdContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCancelar)
                        .addGap(49, 49, 49)
                        .addComponent(btnOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxIdContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
         if (proveedores.getIdProveedor()> 0) {
            proveedores.setNombreProveedor(txtNombreProveedor.getText());
            //proveedores.setIdContacto(Integer.parseInt(txtIdContacto.getText()));
            int idContacto = this.tablaIdContactoClass[(int) comboBoxIdContacto.getSelectedIndex()];
            proveedores.setIdContacto(idContacto);
            proveedores.setActivo(1);
            
            if (proveedores.Update()) {
                JOptionPane.showMessageDialog(null, "Proveedor actualizado correctamente");
                this.dispose();
            }

        } else {
             int idContacto = this.tablaIdContactoClass[(int) comboBoxIdContacto.getSelectedIndex()];
            if (new Proveedores(0,
                    txtNombreProveedor.getText(),
                    //Integer.parseInt(txtIdContacto.getText()),
                    idContacto,
                    1).Add()) {
                JOptionPane.showMessageDialog(null, "Proveedor agregado correctamente");
                this.dispose();
            } else {
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmNMProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmNMProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmNMProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmNMProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                frmNMProveedores dialog = new frmNMProveedores(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> comboBoxIdContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreProveedor;
    // End of variables declaration//GEN-END:variables
}
